name: Advinst Action Demo
on: [workflow_dispatch]
jobs:
  advinst-com-demo:
    runs-on: windows-latest
    name: Advinst COM Demo
    steps:
      - name: Deploy Advinst
        uses: caphyon/advinst-github-action@main
        with:
          advinst-version: '19.0'
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          advinst-enable-com: 'true'
      - name: Use Advinst COM
        shell: pwsh
        run: |
          $advinst = new-object -comobject AdvancedInstaller
          write-host '$advinst.LicenseInfo.Type'
  aiproj-demo:
    runs-on: windows-latest
    name: Build Visual Studio Project (aiproj)
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Deploy Advinst
        uses: caphyon/advinst-github-action@main
        with:
          advinst-version: '19.0'
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }} 
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build app for release
        run: msbuild ${{ github.workspace }}\MyAwesomeApp\MyAwesomeApp.sln
      