name: Powershell Automation Demo
on: [workflow_dispatch]
jobs:
  advinst-com-demo:
    runs-on: windows-latest
    name: Advinst Automation Demo
    steps:
      - name: Deploy Advinst
        uses: caphyon/advinst-github-action@main
        with:
          advinst-version: '19.0'
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          advinst-enable-automation: 'true'
      - name: Use Advinst Automation
        shell: pwsh
        run: |
          # Load the AIP project from checkout location 
          $aipPath = join-path $env:GITHUB_WORKSPACE "simple.aip";
          Write-Host "AIP: $aipPath";

          $advinst = new-object -com advancedinstaller;
          $project = $advinst.LoadProject($aipPath);
          $productDetails = $project.ProductDetails;

          # Bump the ProductVersion
          $productDetails.Version = "1.2.0";
          Write-Host "Version: $productDetails.Version";

          # Build the project
          $project.Build();

      