name: Build AIP and sign using a PFX certificate stored in Secrets
on: [workflow_dispatch]
jobs:
  advinst-aip-build-demo:
    runs-on: windows-latest
    name: Sign Setup Demo
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Create PFX certificate from BASE64_PFX_CONTENT secret
        id: create-pfx
        shell: pwsh
        env:
          PFX_CONTENT: ${{ secrets.BASE64_PFX_CONTENT }} 
        run: |
          $pfxPath = Join-Path -Path $env:RUNNER_TEMP -ChildPath "cert.pfx"; 
          $encodedBytes = [System.Convert]::FromBase64String($env:PFX_CONTENT); 
          Set-Content $pfxPath -Value $encodedBytes -AsByteStream;
          Write-Output "::set-output name=PFX_PATH::$pfxPath";
      
      - name: Build and sign AIP
        uses: caphyon/advinst-github-action@v1.0
        env:
          PFX_PATH: ${{ steps.create-pfx.outputs.PFX_PATH }}
        with:
          advinst-version: '19.0'
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          aip-path: ${{ github.workspace }}\digital signature.aip
          aip-build-name: DefaultBuild
          aip-package-name: setup.msi
          aip-output-dir:  ${{ github.workspace }}\setup
          aip-commands: |
            SetSig
            SetDigitalCertificateFile -file "${{ env.PFX_PATH }}"

      - name: Publish setup artifact
        uses: actions/upload-artifact@v2
        with:
          name: setup
          path: ${{ github.workspace }}\setup\setup.msi

      - name: Delete PFX certificate
        shell: pwsh
        env:
          PFX_PATH: ${{ steps.create-pfx.outputs.PFX_PATH }}
        run: |
          Remove-Item -Path $env:PFX_PATH;
