name: Powershell Automation Demo
on: [workflow_dispatch]
jobs:
  advinst-com-demo:
    runs-on: windows-latest
    name: Advinst COM Demo
    steps:
      - name: Deploy Advinst
        uses: caphyon/advinst-github-action@main
        with:
          advinst-version: '19.0'
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          advinst-enable-com: 'true'
      - name: Use Advinst Automation
        shell: pwsh
        run: |
          $advinst = new-object -comobject AdvancedInstaller
          write-host '$advinst.LicenseInfo.Type'
      