name: Advinst Action Demo
on: [workflow_dispatch]
jobs:
  advinst-action-demo:
    runs-on: windows-latest
    name: Advinst Action Demo
    steps:
      - name: Use Advinst
        uses: caphyon/advinst-github-action@main
        with:
          advinst-version: '19.0'
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          advinst-enable-com: 'true'
      - name: Use Advinst COM
        shell: pwsh
        run: |
          $advinst = new-object -com-object AdvancedInstaller
          write-host '$advinst.LicenseInfo'