name: Build Advanced INstaller Visual Studio Project (AIPROJ)
on: [workflow_dispatch]
jobs:
  aiproj-demo:
    runs-on: windows-latest
    name: Build Visual Studio Project (aiproj)
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        
      - name: Deploy latest advinst version
        uses: caphyon/advinst-github-action@v1.0
        with:
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }} 
          
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Build app
        run: msbuild ${{ github.workspace }}\MyAwesomeApp\MyAwesomeApp.sln
        
      - name: Publish setup artifact
        uses: actions/upload-artifact@v2
        with:
          name: MyAwesomeApp-Setup
          path: ${{ github.workspace }}\MyAwesomeApp\MyAwesomeApp Installer\MyAwesomeApp Installer-SetupFiles\MyAwesomeApp Installer.msi 
