name: Advinst Action Demo
on: [workflow_dispatch]
jobs:
  advinst-action-demo:
    runs-on: windows-latest
    name: Advinst Action Demo
    steps:
      - name: Use Advinst
        uses: Caphyon/advinst-github-action@latest
      
