name: Build AIP and sign using Azure Key Vault Secret
on: [workflow_dispatch]
jobs:
  advinst-aip-build-demo:
    runs-on: windows-latest
    name: Sign Setup Demo
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Build and sign AIP
        uses: caphyon/advinst-github-action@v1.0
        with:
          advinst-version: '20.1'
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          aip-path: ${{ github.workspace }}\test azure key vault.aip
          aip-build-name: DefaultBuild
          aip-package-name: setup.msi
          aip-output-dir:  ${{ github.workspace }}\setup
          aip-commands: |
            SetSig
            SetAzureKeyVaultSecret  "${{ secrets.AZURE_KEY_VAULT_SECRET }}"

      - name: Publish setup artifact
        uses: actions/upload-artifact@v2
        with:
          name: setup
          path: ${{ github.workspace }}\setup\setup.msi

